# Generated by Django 5.1.4 on 2025-03-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scent_family', models.CharField(max_length=50)),
                ('notes_top', models.CharField(max_length=200)),
                ('notes_middle', models.CharField(max_length=200)),
                ('notes_base', models.CharField(max_length=200)),
                ('occasion', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('longevity', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
