# Generated by Django 5.1.4 on 2025-06-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_referraloffer_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.customer'),
        ),
    ]
